language: go

go:
  - master

after_install:
  - go get -u github.com/golang/lint/golint
  - go get github.com/fzipp/gocyclo
  - gofmt -l . | wc -l | awk '{if ($1 != 0) print "ERROR"; else print "OK"}' | grep -v 'ERROR'
  - golint -set_exit_status ./...
  - gocyclo --over 10 . | wc -l | awk '{if ($1 != 0) print "ERROR"; else print "OK"}' | grep -v 'ERROR'
