server:
  hostbase:
    port: "1323"
    host: "127.0.0.1"
  logs:
    access: "/home/igor/access_log"
database:
  user: "moon"
  password: "123"
  dbname: "moondb"
  dialect: "mysql"
  max_open_conns: 10