server:
  hostbase:
    port: "1323"
    host: "127.0.0.1"
  logs:
    access: "/var/log/mooncore/access_log"
database:
  user: "root"
  password: "123"
  dbname: "moondb"
  dialect: "mysql"
  max_open_connections: 10