server:
  hostbase:
    port: "1323"
    host: "127.0.0.1"
  auth:
    lifetime: 72
    secret: "8f2b55f8971c6c3b2b4d18359a9e0e4806a6bc4d"
  api_prefix: "/api"
database:
  user: "root"
  dbname: "moondb"
  dialect: "mysql"
  max_open_conns: 10
logs:
  access: "/var/log/mooncore/access.log"
  main: "/var/log/mooncore/main.log"
